# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: videlicet
email: videlicet2017@gmail.com
description: > 
  A one off vidding zine, edited by lim
keywords: [vidding, fandom, fanvids, vidders, vidding, fans, critique, love]
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://limvids.net" # the base hostname & protocol for your site
permalink: none
defaultpic: /assets/pics/site/default.jpg

collections:
  people:
    output: true
    permalink: /about/people/:path/

#site nav - 
nav:
 - text: all
   url: /articles
 - text: vids
   url: /articles/vids/
 - text: vidding
   url: /articles/vidding
 - text: about
   url: /about/


# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge


